# -*- coding: utf-8 -*-
"""api_grok_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0aK4IreWIRaI0mUgSH9ByxXnedozxmj
"""

# app.py
# A simple Streamlit chatbot application using LangChain and Groq.

import streamlit as st
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import Runnable

# --- Core Chatbot Logic ---

def get_chatbot_chain(api_key: str) -> Runnable:
    """
    Creates and returns a LangChain Runnable sequence for the chatbot.

    This function sets up the language model (LLM), the prompt template,
    and the output parser, then chains them together.

    Args:
        api_key: The Groq API key for authentication.

    Returns:
        A LangChain Runnable object.
    """
    # Initialize the LLM with the provided Groq API key and desired model
    llm = ChatGroq(
        model_name="llama-3.3-70b-versatile",
        groq_api_key=api_key
    )

    # Define the structure of the prompt sent to the LLM
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", "You are a helpful and friendly assistant."),
        ("user", "{question}")
    ])

    # Define the output parser to convert the LLM's response to a string
    output_parser = StrOutputParser()

    # Chain the components together to create the final processing pipeline
    return prompt_template | llm | output_parser


# --- Streamlit User Interface ---

# Configure the Streamlit page
st.set_page_config(page_title="Groq Chatbot", page_icon="🤖")
st.title("🤖 Chatbot with LangChain & Groq")
st.caption("A fast and free AI assistant powered by Groq's LPU.")

# Use a sidebar for the API key input for better layout
with st.sidebar:
    st.header("Configuration")
    groq_api_key = st.text_input("Enter your Groq API Key", type="password")
    st.markdown("[Get a free Groq API key](https://console.groq.com/keys)")

# Initialize chat history in the session state if it doesn't exist
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hello! How can I help you today?"}
    ]

# Display past chat messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# Handle user input
if prompt := st.chat_input("Type your message..."):
    # Check if the API key is provided
    if not groq_api_key:
        st.error("⚠️ Please enter your Groq API key in the sidebar to continue.")
        st.stop() # Stop execution if no key is provided

    # Add user message to history and display it
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Show a thinking spinner while generating the response
    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            # Create the chain and invoke it
            chain = get_chatbot_chain(groq_api_key)
            bot_reply = chain.invoke({"question": prompt})
            st.markdown(bot_reply)

    # Add bot reply to history
    st.session_state.messages.append({"role": "assistant", "content": bot_reply})